### ISSUE TITLE
Update Instagram Icon

### ISSUE THREAD

**Issue by DanielSokil** [edent/SuperTinyIcons#106]
## The icon I want is:

* Name: Instagram
* URL: https://www.instagram.com/
* Link to icon: https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg

![instagram](https://user-images.githubusercontent.com/24403355/33800842-566c09d8-dd17-11e7-88ff-be7f30481d67.png)

**Comment by arturoacevedob** [comment]
I've tried to do it and it ends up over 1KB.

In order to keep our icons under 1KB and provide a consistent look among others, we use the monochrome glyph provided by Instagram itself.
https://en.instagram-brand.com/assets/glyph-icon

I'm currently revising the icons and made this to sit in between:

![instagram](https://user-images.githubusercontent.com/19752150/33802409-759e832e-dd3c-11e7-9522-7a538e0cdb04.png)

**Comment by arturoacevedob** [comment]
Should we use a squircle or not? @edent 

![instagram](https://user-images.githubusercontent.com/19752150/33802636-c9521932-dd40-11e7-8443-5aed491072b5.png) ![instagramn](https://user-images.githubusercontent.com/19752150/33802637-cc84c1ae-dd40-11e7-8261-788d2b7b1d71.png)

We save 90 bytes without it.

**Comment by sanmai-NL** [comment]
Though I am not very happy to see the original design be crushed like this, rationally I favor the minimal version without squircle.

1. The outer border is no squircle either.
2. At the natural size the difference between the versions with and without squircle is even harder to notice than at the enlarged size in your post, @arturoacevedob.

**Comment by arturoacevedob** [comment]
I wasn’t happy either, but gradients take a lot of lines and we’d also need a clipping mask around it.

**Comment by edent** [comment]
The brand guidelines are at https://en.instagram-brand.com/assets/glyph-icon

**Comment by edent** [comment]
Fixed in #112
