### ISSUE TITLE
Quality problems with the new Google icons

### ISSUE THREAD

**Issue by logiclrd** [edent/SuperTinyIcons#480]
A PR with new Google icons was recently merged. I was concerned about (albeit minor) quality issues during review of the PR, but wasn't able to give it my full attention. I've gone and taken a close look at the Google icons after the fact, and have found some quality issues:

google.svg:
![image](https://user-images.githubusercontent.com/2349379/98514626-5fbd9780-222f-11eb-9370-0d0f4647e5d4.png)

google_calendar.svg:
![image](https://user-images.githubusercontent.com/2349379/98514805-ab704100-222f-11eb-872f-5325245ece85.png)

google_play.svg:
![image](https://user-images.githubusercontent.com/2349379/98515061-191c6d00-2230-11eb-8c50-920014b2db93.png)
![image](https://user-images.githubusercontent.com/2349379/98515072-1c175d80-2230-11eb-9ead-992d7b227830.png)

gmail.svg:
![image](https://user-images.githubusercontent.com/2349379/98515546-d0b17f00-2230-11eb-9a99-10c57db52a4d.png)

There's one more, but I'm not 100% certain of it:

google_plus.svg:
![image](https://user-images.githubusercontent.com/2349379/98516777-8b8e4c80-2232-11eb-9b08-5b9bc4c4849e.png)

I've had a hard time tracking down official Google+ logos, no doubt because of how long it has been defunct. Most seem to be a straight 90 degree corner there. Some are rounded, but the rounding is as if the G were carved out of a perfect circle, which is also not reflected in google_plus.svg here. It looks like the final part of the curve leading up to the 90 degree turn got turned into a straight line segment somehow.

**Comment by edent** [comment]
I think ignore the G+ as it is defunct. But very happy for you to correct the new Google ones.

**Comment by logiclrd** [comment]
I'll take a look when I have the time :-)

**Comment by jonatjano** [comment]
Hello,
I was the one who made the PR in question, I tried to reduce these problems after you pointed them but I didn't see I left so much, thank you for your review.

Could you tell me which viewer you're using please because I didn't get most of the issues you mentioned then.

Since you seem to be ready to do a PR for these, I'll give you some informations on the icons modified by the PR :

Gmail : 
The red DO go behind the yellow, that's the solution I found to the rendering quirk making white lines between two blocks with exact same coordinates (like the issue you found in google_calendar between green and red), but It is not visible in the renderers I use to qualiity check what I do (`Firefox 83.0b9`, `Inkscape 0.92.3 (2405546, 2018-03-11)` and `Eye of gnome 3.28.1`)
![image](https://user-images.githubusercontent.com/17279801/98527438-50fcd200-227b-11eb-981d-6ff772e64dac.png)
I used this technique in all of them, for exemple in gmail : red goes behind dark red and yellow, blue goes behind dark red, green goes behind yellow

Google Calendar : 
Sorry for the 1, I'm really bad with characters and didn't see the little bump :pray: 
For the green/red white line, it's here because I didn't use the technique mentioned above because I couldn't find a way to do it without adding a big lump of bytes.

**Comment by logiclrd** [comment]
I am just using Google Chrome, pointed directly at the .svg files. In the case of the red peeking out from behind the yellow, it only shows up when it's _not_ zoomed in -- in a close-up like you posted, it does render perfectly, but when it's a regular sized view, something about the way it renders means that a hint of red gets mixed in along the yellow's edge.
