### ISSUE TITLE
Mastodon Icon thoughts

### ISSUE THREAD

**Issue by jmb** [edent/SuperTinyIcons#693]
I was playing with the mastodon icon elsewhere and tried to change the colour/fill. It caused problems with the two paths so I investigated whether you could cut out the 'm' rather than draw it on... turns out you can! This version comes out 13 bytes larger than the current icon, so not sure if you want a PR for it or not...
![mastodon2](https://user-images.githubusercontent.com/110238/207888956-21211675-8db3-42fd-869f-802b0c5652d5.svg)

**Comment by jmb** [comment]
Here is my source:
`<svg xmlns="http://www.w3.org/2000/svg"
aria-label="Mastodon" role="img"
viewBox="0 0 512 512"
fill="#fff"><rect
width="512" height="512"
rx="15%"/><path fill="#3088d4" fill-rule="evenodd" d="M409 290c-5 24-43 50-85 56-86 11-137-6-137-6 3 13-4 54 70 52 31 0 58-7 58-7l2 27c-51 24-107 15-140 6-67-17-79-90-81-162v-59c0-74 49-96 49-96 50-24 180-22 222 0 0 0 49 22 49 96 0 0 1 55-7 93z M358 202v91h-35v-88c0-18-8-27-23-27-18 0-27 11-27 33v47h-34v-47c0-22-9-33-27-33-15 0-23 9-23 27v88h-35v-91c0-18 5-60 52-60 39 0 50 37 50 37s10-37 50-37c45 0 52 42 52 60z" /></svg>`

**Comment by kuubeu** [comment]
Mastodon have recently [updated their logo](https://blog.joinmastodon.org/2022/06/mastodon-branding-updates/), so updating the old one probably doesn't make much sense. Do you think you could tackle updating the current icon?

By the way, instead of using `fill-rule="evenodd"`, you can reverse the instruction order, and it will automatically substract from the path behind it. So if the original path follows the shape _clockwise_, the path you want to substract has to be defined _counterclockwise_. Sadly, I haven't seen any good tools for this.

Also when pasting code here you can use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks):
````
```svg
<your code>
```
````

**Comment by jmb** [comment]
Thanks for the comment! I'll check out the new logo. I tried the opposite direction path and it came out longer than the extra `fill-mode="even odd"` so left it with that! 🙂
