### ISSUE TITLE
Small Icon for Buildbot

### ISSUE THREAD

**Issue by tardyp** [edent/SuperTinyIcons#89]
Hi, I am the maintainer of the [Buildbot](http://buildbot.net) Continuous Integration framework.

> Want more icons? Tell me by raising an issue!

Well.. in that case...

Our logo was designed probably a decade ago using blender. (sic)
https://github.com/buildbot/buildbot-media/blob/master/images/icon.blend
<img src="https://raw.githubusercontent.com/buildbot/buildbot-media/master/coordinating-parallel-builds-with-buildbot/pictures/nut.png" width="256">

As our community is mostly release engineers, we have zero people with the skill to modernize the logo.

So if you get bored, your challenge of the night is to get this icon under 1k with svg (and maybe modernize it a bit)

**Comment by arturoacevedob** [comment]
I'm down. Should be quick, and it's always a pleasure to design for open source.

**Comment by arturoacevedob** [comment]
![nutnew](https://user-images.githubusercontent.com/19752150/33402780-5201afd4-d523-11e7-88c4-4f416566c26c.png)

![nutnew2](https://user-images.githubusercontent.com/19752150/33403150-d06a7d3c-d524-11e7-9406-8bdfdb398a7e.png)

**Comment by tardyp** [comment]
@arturoacevedob thank you very much for your work! 

I have started a discussion with my community to let them choose. I am very happy with the design, I slighly prefer the second version.
Could you share the svg of it?

I can see that the png does not scale down that well. I don't know if the svg will scale better.

<div><img src="https://user-images.githubusercontent.com/109859/33430577-4f8daf06-d5d1-11e7-96b4-b7255b87209c.png" width="256">
<img src="https://user-images.githubusercontent.com/109859/33430577-4f8daf06-d5d1-11e7-96b4-b7255b87209c.png" width="64">
<img src="https://user-images.githubusercontent.com/109859/33430577-4f8daf06-d5d1-11e7-96b4-b7255b87209c.png" width="32">
<img src="https://user-images.githubusercontent.com/109859/33430577-4f8daf06-d5d1-11e7-96b4-b7255b87209c.png" width="16"></div>

**Comment by arturoacevedob** [comment]
Glad it's liked.

The second version is a safe bet, but keep in mind votes are in favor of the first.

I made a couple of comments in your thread, in which I said that I'll tweak the shapes for visibility at small sizes, because one shape and sometimes color doesn't fit all. Plus the temporary background is taking space. 

I can't attach SVG here, so here the code:

Purple
``<svg width="284" height="299" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" aria-label="Nut" role="img"><path d="M0 205.6v-44L103.9 255v44L0 205.6z" fill="#40238f"/><path d="M103.9 255l141.9-34.2v44l-142 34.2v-44z" fill="#532eb8"/><path d="M245.8 220.8v44l38-127.5v-44l-38 127.5z" fill="#2e1966"/><path d="M180 0l103.8 93.3-38 127.5-142 34.2L0 161.6 38 34.2 180 0zm-3.8 74.1c32.8 17 44 54.7 25 84.2-18.8 29.4-60.8 39.5-93.6 22.5s-44-54.7-25-84.1C101.3 67.2 143.3 57 176.1 74z" fill="#a895db"/><path d="M76.2 145a56 56 0 0 1 6.3-48.3c19-29.5 61-39.6 93.7-22.6 28 14.6 40.3 44.3 31.4 71a63 63 0 0 0-31.4-35.8c-32.8-17-74.8-6.9-93.7 22.6a58.6 58.6 0 0 0-6.3 13.1z" fill="#ffffb3"/><clipPath id="a"><path d="M76.2 145a56 56 0 0 1 6.3-48.3c19-29.5 61-39.6 93.7-22.6 28 14.6 40.3 44.3 31.4 71a63 63 0 0 0-31.4-35.8c-32.8-17-74.8-6.9-93.7 22.6a58.6 58.6 0 0 0-6.3 13.1z"/></clipPath><g clip-path="url(#a)"><path d="M176.2 91.2c32.8 17 44 54.7 25 84.2-18.8 29.4-60.8 39.5-93.6 22.5s-44-54.7-25-84.2c18.8-29.4 60.8-39.5 93.6-22.5z" fill="#5c33cc"/></g></svg>``

Blue
``<svg width="284" height="299" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" aria-label="Nut" role="img"><path d="M0 205.6v-44L103.9 255v44L0 205.6z" fill="#24478F"/><path d="M103.9 255l141.9-34.2v44l-142 34.2v-44z" fill="#2e5cb8"/><path d="M245.8 220.8v44l38-127.5v-44l-38 127.5z" fill="#193366"/><path d="M180 0l103.8 93.3-38 127.5-142 34.2L0 161.6 38 34.2 180 0zm-3.8 74.1c32.8 17 44 54.7 25 84.2-18.8 29.4-60.8 39.5-93.6 22.5s-44-54.7-25-84.1C101.3 67.2 143.3 57 176.1 74z" fill="#8da6d8"/><path d="M76.2 145a56 56 0 0 1 6.3-48.3c19-29.5 61-39.6 93.7-22.6 28 14.6 40.3 44.3 31.4 71a63 63 0 0 0-31.4-35.8c-32.8-17-74.8-6.9-93.7 22.6a58.6 58.6 0 0 0-6.3 13.1z" fill="#FFE14C"/><clipPath id="a"><path d="M76.2 145a56 56 0 0 1 6.3-48.3c19-29.5 61-39.6 93.7-22.6 28 14.6 40.3 44.3 31.4 71a63 63 0 0 0-31.4-35.8c-32.8-17-74.8-6.9-93.7 22.6a58.6 58.6 0 0 0-6.3 13.1z"/></clipPath><g clip-path="url(#a)"><path d="M176.2 91.2c32.8 17 44 54.7 25 84.2-18.8 29.4-60.8 39.5-93.6 22.5s-44-54.7-25-84.2c18.8-29.4 60.8-39.5 93.6-22.5z" fill="#334dcc"/></g></svg>``

**Comment by edent** [comment]
I'm closing this so you can carry on discussion over on https://github.com/buildbot/buildbot/issues/3785 :-)
